apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sagan-renderer
  name: sagan-renderer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sagan-renderer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sagan-default: "true"
        io.kompose.service: sagan-renderer
    spec:
      containers:
        - env:
            - name: JBP_CONFIG_OPEN_JDK_JRE
              value: '{jre: {version: 11.+}}'
            - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
              value: '{enabled: false}'
            - name: SPRING_PROFILES_ACTIVE
              value: cloud,production
          image: sagan-renderer
          name: sagan-renderer
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
