# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "default-terraform-state"
    dynamodb_table = "default-state-locks"
    encrypt        = true
    key            = "./dev/terraform.tfstate"
    profile        = "default"
    region         = "ap-northeast-1"
  }
}
